# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "roboxes/centos8"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../", "/bindfs",
    type: "rsync",
    rsync__auto: false,
    rsync__exclude: ["vagrant"],
    rsync__args: ["-av", "--delete-after"]

  config.vm.provider "virtualbox" do |v|
    v.name = "bindfs-centos8"
  end
  config.vm.provider "libvirt" do |v|
    v.driver = if File.exist?('/dev/kvm') then 'kvm' else 'qemu' end
  end

  config.vm.provision "shell", inline: <<-SHELL
    # CentOS 8 is EOL
    # https://www.cyberithub.com/solved-failed-to-download-metadata-for-repo-appstream/
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

    yum install -y fuse fuse-devel gcc make pkg-config ruby valgrind
    echo user_allow_other > /etc/fuse.conf
  SHELL
end
