# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "roboxes/alpine315"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../", "/bindfs",
    type: "rsync",
    rsync__auto: false,
    rsync__exclude: ["vagrant"],
    rsync__args: ["-av", "--delete-after"]

  config.vm.provider "virtualbox" do |v|
    v.name = "bindfs-alpine315"
  end

  config.vm.provision "shell", reboot: true, inline: <<-SHELL
    apk add rsync gcc make musl-dev linux-headers fuse3 fuse3-dev ruby valgrind
    echo user_allow_other > /etc/fuse.conf
    echo fuse > /etc/modules-load.d/fuse.conf
  SHELL
end
