# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "roboxes/debian10"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../", "/bindfs",
    type: "rsync",
    rsync__auto: false,
    rsync__exclude: ["vagrant"],
    rsync__args: ["-av", "--delete-after"]

  config.vm.provider "virtualbox" do |v|
    v.name = "bindfs-debian10"
  end
  config.vm.provider "libvirt" do |v|
    v.driver = if File.exist?('/dev/kvm') then 'kvm' else 'qemu' end
  end

  config.vm.provision "shell", reboot: true, inline: <<-SHELL
    export DEBIAN_FRONTEND='noninteractive'
    apt-get update
    apt-get install -y fuse3 libfuse3-dev build-essential pkg-config ruby valgrind
    apt-get clean
    echo user_allow_other > /etc/fuse.conf
  SHELL
end
