# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "roboxes/openbsd7"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../", "/bindfs",
    type: "rsync",
    rsync__auto: false,
    rsync__exclude: ["vagrant"],
    rsync__args: ["-av", "--delete-after"]

  config.vm.provider "virtualbox" do |v|
    v.name = "bindfs-openbsd7"
  end

  config.vm.provision "shell", inline: <<-SHELL
    chmod a+rw /dev/fuse0

    pkg_add -I ruby-3.1.2
    ln -sf /usr/local/bin/ruby31 /usr/local/bin/ruby
  SHELL
end
