# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/precise64"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../", "/bindfs",
    type: "rsync",
    rsync__auto: false,
    rsync__exclude: ["vagrant"],
    rsync__args: ["-av", "--delete-after"]

  config.vm.provider "virtualbox" do |v|
    v.name = "bindfs-precise64"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y fuse libfuse-dev build-essential pkg-config ruby1.9.3 valgrind
    apt-get clean
    adduser vagrant fuse
    echo user_allow_other > /etc/fuse.conf
  SHELL
end
